server:
  port: 8082

spring:
  application:
    name: route-planning-service
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password
    connection-timeout: 3s
    max-transaction-retry-time: 3s

management:
  health:
    neo4j:
      enabled: false
